enum ConfigKey {
    NODE_ENV = 'NODE_ENV',
    LOG_LEVEL = 'LOG_LEVEL',
    PORT = 'PORT',
    BASE_PATH = 'BASE_PATH',
    CORS_WHITE_LIST = 'CORS_WHITE_LIST',
    MAX_REQUEST_SIZE = 'MAX_REQUEST_SIZE',
    DB_NAME = 'DB_NAME',
    DB_USERNAME = 'DB_USERNAME',
    DB_HOST = 'DB_HOST',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_PORT = 'DB_PORT',
}

export default ConfigKey;
