enum ConfigKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    BASE_PATH = 'BASE_PATH',
    LOG_LEVEL = 'LOG_LEVEL',
    LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
    DATABASE = 'DATABASE',
    JWT_SECRET_ACCESS_TOKEN_KEY = 'JWT_SECRET_ACCESS_TOKEN_KEY',
    JWT_SECRET_REFRESH_TOKEN_KEY = 'JWT_SECRET_REFRESH_TOKEN_KEY',
    TOKEN_EXPIRED_IN = 'TOKEN_EXPIRED_IN',
    REFRESH_TOKEN_EXPIRED_IN = 'REFRESH_TOKEN_EXPIRED_IN',
    CORS_WHITE_LIST = 'CORS_WHITE_LIST',
    MAX_REQUEST_SIZE = 'MAX_REQUEST_SIZE',
    DB_NAME = 'DB_NAME',
    DB_USERNAME = 'DB_USERNAME',
    DB_HOST = 'DB_HOST',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_PORT = 'DB_PORT',
}

export default ConfigKey;
